name: Trigger auto deployment for appback

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/appback-AutoDeployTrigger-40712897-b0d7-437a-bf01-2cb47a683be7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image into ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/cmp-back:latest
          file: Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APPBACK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPBACK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPBACK_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/cmp-back:latest
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
          environment_variables: |
            NODE_ENV=production
            PORT=4000
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
            AZURE_STORAGE_SAS_TOKEN=${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
          container_name: appback
          target_port: 4000
          ingress: external
          min_replicas: 1
          max_replicas: 1
          cpu: 0.5
          memory: 1Gi
          startup_command: npm run start:prod
          startup_timeout: 300
          liveness_probe: |
            {
              "httpGet": {
                "path": "/graphql",
                "port": 4000
              },
              "initialDelaySeconds": 30,
              "periodSeconds": 10
            }
          readiness_probe: |
            {
              "httpGet": {
                "path": "/graphql",
                "port": 4000
              },
              "initialDelaySeconds": 5,
              "periodSeconds": 5
            }


