name: Trigger auto deployment for cmpappback

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cmpappback-AutoDeployTrigger-364fd8c0-20e1-442a-b566-99959bc2df04.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CMPAPPBACK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CMPAPPBACK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CMPAPPBACK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: backcont.azurecr.io
          registryUsername: ${{ secrets.CMPAPPBACK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CMPAPPBACK_REGISTRY_PASSWORD }}
          containerAppName: cmpappback
          resourceGroup: grupocmp
          imageToBuild: backcont.azurecr.io/cmpappback:${{ github.sha }}


